### PR TITLE
updating

### PR DESCRIPTION
**Pull request by brandon-005**

### CODE REVIEW

**Comment by ha6000** [comment]
uh, what is this?

**Comment by brandon-005** [comment]
Updating the other branch with the changes from main since it's outdated

**Comment by ha6000** [comment]
what is this branch for?

**Comment by brandon-005** [comment]
The upcoming v2.1.0 release, however it might be in my best interest to delete this branch and start fresh with a new one

**Comment by ha6000** [comment]
ah ok

**Pull request closed without merging**
